export const SAVE_TO_CART = "SAVE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const INIT_ADDRESS_FORM = "INIT_ADDRESS_FORM";
export const RESET_ADDRESS_FORM = "RESET_ADDRESS_FORM";
export const SET_ADDRESS = "SET_ADDRESS";
export const AUTHENTICATE = "AUTHENTICATE";
export const LOGOUT = "LOGOUT";
